### ISSUE TITLE
Volume de la musique

### ISSUE THREAD

**Issue by JeffWooden** [Sworder71/Jupiter#2]
Lorsque l'on change le volume du bot lors d'une musique et si il y en a une qui suit, le volume est réinitialisé.

**Comment by Sworder71** [comment]
Salut, celà est normal vu que c'est le volume du stream et pas du bot.

**Comment by JeffWooden** [comment]
Oh d'accord. Du coup vu que ce n'est pas trop gênant je baisse manuellement le son.
J'ai envoyé une issue "au cas où" si ceci n'était pas normal.

**Comment by Sworder71** [comment]
Ok, pas de soucis.
