### ISSUE TITLE
Erreur quand je fais prefix+play

### ISSUE THREAD

**Issue by pyjamableu** [Sworder71/Jupiter#3]

**Comment by Sworder71** [comment]
Quel type d'erreur s'agit-il ?

**Comment by pyjamableu** [comment]
je t'envoie un screen, merci de ta réponse rapide

**Comment by Sworder71** [comment]
Ok, pas de soucis.

**Comment by pyjamableu** [comment]
[https://zupimages.net/up/19/11/etzp.jpg](url)

**Comment by pyjamableu** [comment]
nouvelle erreur : 
`[13/03/2019] [Info] Sharding | Shard #0 lancé !
(node:8720) UnhandledPromiseRejectionWarning: Error: Shard 0's process exited before its Client became ready.
    at Shard.once (/home/sebek/donqui/musique/node_modules/discord.js/src/sharding/Shard.js:88:39)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Shard.emit (events.js:211:7)
    at Shard._handleExit (/home/sebek/donqui/musique/node_modules/discord.js/src/sharding/Shard.js:272:10)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
(node:8720) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 27)
`

**Comment by Sworder71** [comment]
Quelle version de **discord.js** utilise tu ?

**Comment by pyjamableu** [comment]
11.4.2

**Comment by Sworder71** [comment]
As-tu modifié le fichier du sharding ?

**Comment by pyjamableu** [comment]
non, du tout juste le config.json

**Comment by Sworder71** [comment]
Installe la version **^11.3.2** et vois si ça marche.
Dans le cas où ça ne marcherais pas, lance le bot depuis le fichier **index.js** si il n'a pas besoin de shards.

Discord.js a pas mal de soucis au niveau du Sharding, la version la plus stable reste la **^11.3.2**

**Comment by pyjamableu** [comment]
Ok merci de ta réponse je te tiens au jus

**Comment by Sworder71** [comment]
Closed due to inactivity.
