### ISSUE TITLE
Bot PARFAIT sauf..... 

### ISSUE THREAD

**Issue by Yourita** [Sworder71/Jupiter#5]
Coucou, ton bot est trop bien, mais ! 
les musique ne sons pas détecter aurais tu un conseil a me donner ? je n'ai pas d'erreur.

![b82a93aee39f27ca1a658cf59f6a0e76](https://user-images.githubusercontent.com/54727469/64138128-ed1b8580-cdfb-11e9-81a6-fcc7bdbc9e14.png)

**Comment by Sworder71** [comment]
Salut, est-ce que ta clé API YouTube est fonctionnelle ? Par ailleurs, ce bot est déprécié, je te déconseille de l'utiliser, passe plutôt pour mon bot Rias.

**Comment by Sworder71** [comment]
Pour inactivité je clos cette issue.
